import { Platform, StyleSheet } from "react-native";

export const C = {
  bg: "#18271f",
  surface: "#22382b",
  lifted: "#2a4332",
  ink: "#f4f2e8",
  muted: "#b1c0b3",
  line: "#3b5140",
  green: "#c5dfa8",
  greenInk: "#294425",
  coral: "#ffb297",
  purple: "#ddc6ec",
  purpleBg: "#40344b",
  water: "#213f47",
};
export const fonts = {
  body: "DMSans_400Regular",
  medium: "DMSans_500Medium",
  bold: "DMSans_700Bold",
  serif: "DMSerifDisplay_400Regular",
};
export const s = StyleSheet.create({
  outer: { flex: 1, backgroundColor: "#101c16", alignItems: "center" },
  app: {
    flex: 1,
    width: "100%",
    maxWidth: 480,
    backgroundColor: C.bg,
    borderLeftWidth: Platform.OS === "web" ? 1 : 0,
    borderRightWidth: Platform.OS === "web" ? 1 : 0,
    borderColor: C.line,
  },
  text: { color: C.ink, fontFamily: fonts.body, fontSize: 16, lineHeight: 24 },
  muted: {
    color: C.muted,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 21,
  },
  tiny: {
    color: C.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    lineHeight: 18,
  },
  title: { color: C.ink, fontFamily: fonts.bold, fontSize: 25, lineHeight: 33 },
  heading: {
    color: C.ink,
    fontFamily: fonts.bold,
    fontSize: 18,
    lineHeight: 25,
  },
  serif: {
    color: C.ink,
    fontFamily: fonts.serif,
    fontSize: 34,
    lineHeight: 39,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pad: { paddingHorizontal: 22 },
  stack: { gap: 16 },
  comparisonHeader: { alignItems: "center", gap: 10, paddingVertical: 8 },
  comparisonTitle: {
    color: C.ink,
    fontFamily: fonts.serif,
    fontSize: 30,
    lineHeight: 35,
    textAlign: "center",
  },
  comparisonRow: { flexDirection: "row", alignItems: "stretch", gap: 16 },
  comparisonCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 230,
    paddingHorizontal: 14,
    paddingVertical: 20,
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 18,
    backgroundColor: C.surface,
  },
  comparisonCardPressed: { backgroundColor: C.lifted, borderColor: C.green },
  comparisonLabel: {
    color: C.green,
    fontFamily: fonts.bold,
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.7,
    textTransform: "uppercase",
    textAlign: "center",
  },
  comparisonIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: C.lifted,
    alignItems: "center",
    justifyContent: "center",
  },
  comparisonName: {
    fontFamily: fonts.bold,
    fontSize: 17,
    lineHeight: 23,
    textAlign: "center",
    alignSelf: "stretch",
  },
  comparisonVenue: {
    color: C.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    alignSelf: "stretch",
  },
  comparisonOr: {
    position: "absolute",
    left: "50%",
    top: "50%",
    marginLeft: -16,
    marginTop: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  wordmark: {
    fontFamily: fonts.serif,
    color: C.green,
    fontSize: 30,
    // Override T's 24-point body line height so native text does not clip the serif.
    lineHeight: 40,
    letterSpacing: -1,
  },
  icon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  search: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: C.surface,
    borderRadius: 12,
    paddingHorizontal: 13,
    marginHorizontal: 22,
    marginBottom: 16,
    height: 46,
  },
  input: {
    flex: 1,
    color: C.ink,
    fontFamily: fonts.body,
    fontSize: 16,
    paddingVertical: 10,
    minWidth: 0,
  },
  inputBox: {
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.surface,
    borderRadius: 12,
    color: C.ink,
    fontFamily: fonts.body,
    padding: 14,
    fontSize: 16,
  },
  quick: {
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 22,
    marginBottom: 22,
  },
  quickButton: {
    flex: 1,
    backgroundColor: C.surface,
    minHeight: 42,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
    borderWidth: 1,
    borderColor: C.line,
  },
  quickActive: { backgroundColor: "#3e5b35", borderColor: "#789964" },
  tabs: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    marginHorizontal: 22,
    marginTop: 8,
    marginBottom: 14,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    minHeight: 45,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: C.green },
  pill: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 22,
    backgroundColor: C.bg,
  },
  pillActive: { backgroundColor: C.green, borderColor: C.green },
  pillText: { fontFamily: fonts.medium, fontSize: 14, color: C.ink },
  pillTextActive: { color: C.greenInk },
  primary: {
    minHeight: 52,
    paddingHorizontal: 20,
    borderRadius: 15,
    backgroundColor: C.green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  primaryText: { fontFamily: fonts.bold, fontSize: 16, color: C.greenInk },
  secondary: {
    minHeight: 48,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  card: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 22,
    overflow: "hidden",
    marginBottom: 15,
  },
  cardBody: { padding: 17, gap: 12 },
  photo: { width: "100%", height: 174, backgroundColor: C.lifted },
  save: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.surface,
  },
  score: {
    backgroundColor: "#354d2c",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  scoreText: { fontFamily: fonts.medium, color: C.green, fontSize: 14 },
  niche: {
    backgroundColor: C.purpleBg,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  nicheText: { fontFamily: fonts.medium, color: C.purple, fontSize: 13 },
  eyebrow: {
    color: C.green,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  notice: { borderRadius: 13, backgroundColor: C.surface, padding: 13, gap: 5 },
  nav: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: C.line,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: C.bg,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    minHeight: 56,
    borderRadius: 13,
  },
  navSelected: { backgroundColor: "#344134" },
  navAdd: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.coral,
  },
  navLabel: { color: C.muted, fontFamily: fonts.medium, fontSize: 12 },
  backdrop: {
    flex: 1,
    backgroundColor: "#08110ecc",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  sheet: {
    backgroundColor: C.bg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    width: "100%",
    maxWidth: 480,
    maxHeight: "91%",
    borderWidth: 1,
    borderColor: C.line,
  },
  sheetHeader: {
    paddingHorizontal: 22,
    paddingTop: 15,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sheetBody: { paddingHorizontal: 22, paddingBottom: 32, gap: 18 },
  choice: {
    padding: 20,
    borderRadius: 16,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.line,
    gap: 7,
    minHeight: 90,
  },
  bigNumber: {
    fontFamily: fonts.serif,
    color: C.green,
    fontSize: 76,
    lineHeight: 86,
  },
  avatar: {
    backgroundColor: C.lifted,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  guide: {
    borderWidth: 1,
    borderColor: "#6d855b",
    backgroundColor: "#33482d",
    borderRadius: 21,
    padding: 23,
    gap: 14,
  },
  guideRow: {
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rank: { fontFamily: fonts.serif, fontSize: 29, color: C.green, width: 28 },
  empty: {
    paddingVertical: 45,
    paddingHorizontal: 26,
    gap: 12,
    alignItems: "center",
  },
  toast: {
    position: "absolute",
    bottom: 97,
    left: 22,
    right: 22,
    borderRadius: 14,
    backgroundColor: C.green,
    padding: 15,
    zIndex: 10,
  },
  separator: { height: 1, backgroundColor: C.line, marginVertical: 4 },
});
